### ISSUE TITLE
Getting specific currency

### ISSUE THREAD

**Issue by larevio** [grp-gg/tebex_headless#2]
Hi , im tring to connect tebex api to my website which written in nextjs 

how can i get the packages in the different currencies then the store default currency ? 
and how can i get the packages tax based on customer ip address

**Comment by Tynopia** [comment]
Hi Larevio,

Thank you for bringing this to my attention. I reviewed the [official documentation](https://documenter.getpostman.com/view/10912536/2s9XxvTEmh#e2d98793-eaad-4b07-b10f-97e9c7890795) on Postman and found some information regarding this issue.

Tebex requires basic authentication using both your public and private keys to forward IPs.

I have prepared a brief example illustrating how to set up these keys, which you can find here: https://github.com/grp-gg/tebex_headless?tab=readme-ov-file#ip-forwarding

Please take a moment to review the latest commit to see the changes I made: https://github.com/grp-gg/tebex_headless/commit/930f7276374e7d7c805eb3f77b1b8807080c5f99

Make sure to use the latest package version (1.4.0) available on [npm](https://www.npmjs.com/package/tebex_headless) to access these features.

Once you have set up your keys, you can use the IP parameter in the following functions:

```
GetCategories
GetCategory
GetPackage
GetPackages
CreateBasket
```

Unfortunately, I cannot tell you to what extent Tebex determines the taxes or currency itself. I have not found anything about the currency itself in the Postman documentation.

**Comment by larevio** [comment]
so what we should do about currencies ? 
the documents said [this website ](https://store.mccisland.net/) using headless api 
and it support currencies

**Comment by Tynopia** [comment]
I think you have to implement it on your own. The example website displays the amount in the other currency but automatically switches it back (I think automatically based on your IP) when you're on the checkout page.

Next week, I will try to get in touch with Tebex and inquire about this issue.

![image](https://github.com/grp-gg/tebex_headless/assets/65678882/d5ce9743-7755-4048-ba5d-37f7b565953f)
![image](https://github.com/grp-gg/tebex_headless/assets/65678882/a1248edb-b006-4ead-ae36-55c6f5ac608c)

**Comment by larevio** [comment]
Thanks for answers 

another think i tested ipaddress but it doesn't make it different , in normal request the tax will be set based on your ip location 

but when we change the ipaddress inside request we got the same amount of tax each time

**Comment by Tynopia** [comment]
Which taxes did you apply? Perhaps you could send me the URL to your shop, and I will try it with my IP address and taxes (Germany 19%).

**Comment by Tynopia** [comment]
Hi @larevio,

In the past few days, I've been in communication with Tebex and their developers, and we've implemented some fixes.

Taxes and Country are now successfully determined based on the provided IP address in a basket, as you can see in this [integration test](https://github.com/grp-gg/tebex_headless/blob/main/tests/Basket.test.ts#L46-L53).

However, there are still some issues:

- The currency in packages and baskets is still determined by your currency or webstore settings.
- When you request all packages with the GetCategories or GetPackages functions (but it will work when you provide a basket identifier), the taxes are still based on your IP address.
