### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by IAmEthanTheCoder** [grp-gg/tebex_headless#5]
Is there anyway you can implement a system into this where we can fetch purchases / payments and handle them? For example I can have a central server which can receive and process completed payments and give the player their reward

**Comment by Tynopia** [comment]
Hi @IAmEthanTheCoder,

This isn't a component of the Headless API. The API structure of this is designed for public use, meaning every user can perform the same actions as in the regular store.

For your specific requirements, please check this page: https://docs.tebex.io/plugin/official-plugins.

If you have any further questions or need clarification, feel free to ask.
