### ISSUE TITLE
Global state for `webstoreIdentifier` / `privateKey`

### ISSUE THREAD

**Issue by colinmcdonald22** [grp-gg/tebex_headless#8]
Hi,

We're considering using this library for a project where we'd need to send requests to multiple Tebex stores. Some requests might to go store A, some to store B, etc. As a result, there's some difficulty due to the global state used in this library for `webstoreIdentifier` and `privateKey`.

I believe it'd be _possible_ to wrap this library as follows:

```javascript
async function WrappedAddPackageToBasket(store, ...) {
    SetWebstoreIdentifier(store.webstoreIdentifier);
    SetPrivateKey(store.privateKey);
    const result = await AddPackageToBasket(...);
    SetWebstoreIdentifier("");
    SetPrivateKey("");
    return result;
}
```

However, this isn't a great developer experience - this would have to be done for every function the library exposes. I was wondering if there'd be any interest in refactoring the library to make this use case easier. Two ideas I had were:

* Make a `TebexHeadlessClient` class (or similar) which stores this configuration, rather than storing it globally. We could then create one `TebexHeadlessClient` per underlying Tebex store.
* Allow these parameters to be supplied in each request (ex: `AddPackageToBasket(..., store.webstoreIdentifier)`

Curious to hear your thoughts on this!

**Comment by Tynopia** [comment]
Hi @colinmcdonald22,

I agree with you that using multiple Tebex Stores is not an ideal developer experience.

The goal of this architecture was to simplify usage without requiring global variables, such as an object for the Headless API.

I believe we can implement a class that utilizes the global functions without needing the global webstore identifier or private key.

I'll have a look at that 👍

**Comment by colinmcdonald22** [comment]
Thank you!

**Comment by Tynopia** [comment]
@colinmcdonald22 I updated the architecture to be class-based. You can now use it with `new TebexHeadless(...)` as shown in the README.
